algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

var
       cq,v1,q2,resultado:real
inicio
escreval ("inseria  codigo da peça")
leia(cq)
escreval ("inseria  valor da peça")
leia (v1)
escreval ("inseria  quantidade da peça")
leia(q2)
      //calcular
resultado <- (v1*q2)
escreval(" codigo da peça" ,cq, " seu valor",resultado)



fimalgoritmo
